export const ICONS = {
  check: "/icons/check.svg",
  filter: "/icons/filtro.svg",
  lupa: "/icons/lupa.svg",
  logo_02: '/icons/logo_02.svg',
  consultoria: '/icons/consultoria.svg',
  suporte_tecnico: '/icons/suporte_tecnico.svg',
  microfranquia: '/icons/microfranquia.svg',
  mini_image: '/icons/mini_image.svg',
  left_arrow: '/icons/left_arrow.svg',
  profile_image: '/icons/profile_image.svg',
  remove_profile_image: '/icons/remove_profile_image.svg',
  olho: '/icons/olho.svg',
  olho_fechado: '/icons/olho_fechado.svg',
  check_icon: '/icons/check_icon.svg',
  plano_basic: '/icons/plano_basic.svg',
  plano_pro: '/icons/plano_pro.svg',
  plano_starter: '/icons/plano_starter.svg',
  models: {
    home_based: "/icons/Modelo de negocio/home based.svg",
    home_office: "/icons/Modelo de negocio/home officie.svg",
    loja_fisica: "/icons/Modelo de negocio/Loja fisica.svg",
    quiosque: "/icons/Modelo de negocio/quiosque.svg",
    unidade_movel: "/icons/Modelo de negocio/unidade movel.svg",
  },
  segments: {
    turism_agency: "/icons/Segmentos/Agências de Viagens e Turism.svg",
    foods: "/icons/Segmentos/Alimentação.svg",
    drinks: "/icons/Segmentos/Bebidas.svg",
    beauty: "/icons/Segmentos/beleza.svg",
    house_construction: "/icons/Segmentos/Casa e Construção.svg",
    eletronics: "/icons/Segmentos/Comércio Eletrônico.svg",
    delivery: "/icons/Segmentos/Delivery e Logística.svg",
    education: "/icons/Segmentos/education.svg",
    leisure: "/icons/Segmentos/Lazer e Entretenimento.svg",
    marketing: "/icons/Segmentos/marketing.svg",
    fashion: "/icons/Segmentos/moda.svg",
    pet_shops: "/icons/Segmentos/Pet Shop e Serviços para Animais.svg",
    health: "/icons/Segmentos/saude.svg",
    automotive: "/icons/Segmentos/Serviços Automotivo.svg",
    cleaning: "/icons/Segmentos/Serviços de Limpeza.svg",
    services: "/icons/Segmentos/Serviços e outros.svg",
    finances: "/icons/Segmentos/Serviços Financeiros.svg",
    residential: "/icons/Segmentos/Serviços Residenciais e Reforma.svg",
    computing: "/icons/Segmentos/Tecnologia da Informação.svg",
    clothing: "/icons/Segmentos/vestuario.svg",
  },

  
  IconsCarousel: {
    alimentacao:'icons/IconsCarousel/alimentacao.svg',
    agricultura:'icons/IconsCarousel/agricultura.svg',
    autobolistico:'icons/IconsCarousel/autobolistico.svg',
    bem_estar_animal:'icons/IconsCarousel/bem estar animal.svg',
    conservacao:'icons/IconsCarousel/conservação.svg',
    construcao:'icons/IconsCarousel/construção.svg',
    e_commerce:'icons/IconsCarousel/E-Commerce.svg',
    educação:'icons/IconsCarousel/educação.svg',
    entreterimento:'icons/IconsCarousel/entreterimento.svg',
    financas:'icons/IconsCarousel/finanças.svg',
    fitness:'icons/IconsCarousel/fitness.svg',
    indicados:'icons/IconsCarousel/indicados.svg',
    imobiliaria:'icons/IconsCarousel/imobiliária.svg',
    informatica:'icons/IconsCarousel/informatica.svg',
    lazer:'icons/IconsCarousel/lazer.svg',
    limpeza:'icons/IconsCarousel/limpeza.svg',
    logistica:'icons/IconsCarousel/logistica.svg',
    meio_ambiente:'icons/IconsCarousel/meio ambiente.svg',
    moda:'icons/IconsCarousel/moda.svg',
    praia:'icons/IconsCarousel/praia.svg',
    saude:'icons/IconsCarousel/saude.svg',
    turismo:'icons/IconsCarousel/turismo.svg',
    upload:'icons/IconsCarousel/upload.svg',
},

  overviewImages: {
    arrow:'icons/OverviewImages/arrow.svg',
    double_arrow:'icons/OverviewImages/double-arrow.svg',
    franchise_fee:'icons/OverviewImages/franchise_fee.svg',
    globo:'icons/OverviewImages/globo.svg',
    home:'icons/OverviewImages/home.svg',
    instalation_capital:'icons/OverviewImages/instalation_capital.svg',
    lupa:'icons/OverviewImages/lupa.svg',
    logo_contbank:'icons/OverviewImages/logo_contbank.svg',
    menu:'icons/OverviewImages/menu.svg',
    profile_vector:'icons/OverviewImages/profile_vector.svg',
    star:'icons/OverviewImages/star.svg',
    heart:'icons/OverviewImages/heart.svg',
    check_mark:'icons/OverviewImages/check_mark.svg',
    sede:'icons/OverviewImages/sede.svg',
    store_area:'icons/OverviewImages/store_area.svg',
    upload:'icons/OverviewImages/upload.svg',
    instagram:'icons/OverviewImages/instagram.svg',
    twitter:'icons/OverviewImages/twitter.svg',
    linkedin:'icons/OverviewImages/linkedin.svg',
    youtube:'icons/OverviewImages/youtube.svg',
    warn_vector:'icons/OverviewImages/warn_vector.svg',
    working_capital:'icons/OverviewImages/working_capital.svg',
    profile:'icons/OverviewImages/imagens/profile-2.svg',
    image01:'icons/OverviewImages/imagens/Image01.svg',
    image02:'icons/OverviewImages/imagens/Image02.svg',
    image03:'icons/OverviewImages/imagens/Image03.svg',
  }

};
