export const ICONS = {
    filter: '/icons/filtro.svg',
    lupa: '/icons/lupa.svg',
    check: '/icons/check.svg',
    models: {
        home_based: '/icons/Modelo de negocio/home based.svg',
        home_office: '/icons/Modelo de negocio/home officie.svg',
        loja_fisica: '/icons/Modelo de negocio/Loja fisica.svg',
        quiosque: '/icons/Modelo de negocio/quiosque.svg',
        unidade_movel: '/icons/Modelo de negocio/unidade movel.svg',
    },
    segments: {
        turism_agency: '/icons/Segmentos/Agências de Viagens e Turism.svg',
        foods: '/icons/Segmentos/Alimentação.svg',
        drinks: '/icons/Segmentos/Bebidas.svg',
        beleza: '/icons/Segmentos/beleza.svg',
        casa_construcao: '/icons/Segmentos/Casa e Construção.svg',
        eletronicos: '/icons/Segmentos/Comércio Eletrônico.svg',
        delivery: '/icons/Segmentos/Delivery e Logística.svg',
        education: '/icons/Segmentos/education.svg',
        lazer: '/icons/Segmentos/Lazer e Entretenimento.svg',
        marketing: '/icons/Segmentos/marketing.svg',
        moda: '/icons/Segmentos/moda.svg',
        pet_shops: '/icons/Segmentos/Pet Shop e Serviços para Animais.svg',
        saude: '/icons/Segmentos/saude.svg',
        automotivos: '/icons/Segmentos/Serviços Automotivo.svg',
        limpeza: '/icons/Segmentos/Serviços de Limpeza.svg',
        services: '/icons/Segmentos/Serviços e outros.svg',
        finances: '/icons/Segmentos/Serviços Financeiros.svg',
        residenciais: '/icons/Segmentos/Serviços Residenciais e Reforma.svg',
        informatica: '/icons/Segmentos/Tecnologia da Informação.svg',
        vestuario: '/icons/Segmentos/vestuario.svg',
    }
};