export const ICONS = {
    filter: '/icons/filtro.svg',
    lupa: '/icons/lupa.svg',
    check: '/icons/check.svg',
    models: {
        home_based: '/icons/Modelo de negocio/home based.svg',
        home_office: '/icons/Modelo de negocio/home officie.svg',
        loja_fisica: '/icons/Modelo de negocio/Loja fisica.svg',
        quiosque: '/icons/Modelo de negocio/quiosque.svg',
        unidade_movel: '/icons/Modelo de negocio/unidade movel.svg',
        id_vector: '/icons/Modelo de negocio/id vector.svg',
        set_up: '/icons/Modelo de negocio/set up.svg',
    },
    segments: {
        turism_agency: '/icons/Segmentos/Agências de Viagens e Turism.svg',
        foods: '/icons/Segmentos/Alimentação.svg',
        drinks: '/icons/Segmentos/Bebidas.svg',
        beauty: '/icons/Segmentos/beleza.svg',
        house_construction: '/icons/Segmentos/Casa e Construção.svg',
        eletronics: '/icons/Segmentos/Comércio Eletrônico.svg',
        delivery: '/icons/Segmentos/Delivery e Logística.svg',
        education: '/icons/Segmentos/education.svg',
        leisure: '/icons/Segmentos/Lazer e Entretenimento.svg',
        marketing: '/icons/Segmentos/marketing.svg',
        fashion: '/icons/Segmentos/moda.svg',
        pet_shops: '/icons/Segmentos/Pet Shop e Serviços para Animais.svg',
        health: '/icons/Segmentos/saude.svg',
        automotive: '/icons/Segmentos/Serviços Automotivo.svg',
        cleaning: '/icons/Segmentos/Serviços de Limpeza.svg',
        services: '/icons/Segmentos/Serviços e outros.svg',
        finances: '/icons/Segmentos/Serviços Financeiros.svg',
        residential: '/icons/Segmentos/Serviços Residenciais e Reforma.svg',
        computing: '/icons/Segmentos/Tecnologia da Informação.svg',
        clothing: '/icons/Segmentos/vestuario.svg',

    },
    registered: {
        store: 'icons/Franquias Registradas/loja 1.png',
        flag: 'icons/Franquias Registradas/design/bandeira.svg',
        finger: 'icons/Franquias Registradas/design/dedo.svg',
        desing: 'icons/Franquias Registradas/design/desing.svg',
        home: 'icons/Franquias Registradas/design/home.svg',
        pencil: 'icons/Franquias Registradas/design/lapis.svg',
        trash: 'icons/Franquias Registradas/design/lixo.svg',
        eye: 'icons/Franquias Registradas/design/olho.svg',
        person: 'icons/Franquias Registradas/design/person.svg',
        person1: 'icons/Franquias Registradas/design/person1.svg',
        percentage: 'icons/Franquias Registradas/design/porcentagem.svg',
        arrow: 'icons/Franquias Registradas/design/seta.svg',
        bell: 'icons/Franquias Registradas/design/sino.svg',
        facebok: 'icons/Franquias Registradas/redes sociais/facebook-icon.svg',
        instagram: 'icons/Franquias Registradas/redes sociais/instagram-icon.svg',
        linkedin: 'icons/Franquias Registradas/redes sociais/linkedin-icon.svg',
        tiktok: 'icons/Franquias Registradas/redes sociais/tiktok-icon.svg',
        x: 'icons/Franquias Registradas/redes sociais/x-icon.svg',
        youtube: 'icons/Franquias Registradas/redes sociais/youtube-icon.svg',
        menu: 'icons/Franquias Registradas/design/menu-icon.svg', 
    },

};