export const operations = [
  "Alimentação",
  "Casa e Construção",
  "Comunicação,informática e eletrônicos",
  "Educação",
  "Entretenimento e lazer",
  "Hotelaria e turismo",
  "Limpeza e conservação",
  "Moda",
  "Saúde e Beleza e bem estar",
  "Serviços Automotivos",
  "Serviço e outros negócios",
  "Imobiliário",
  "Finanças e Seguros",
  "Agricultura e Agroindústria",
  "Meio Ambiente",
  "Logística e Transporte",
  "Bem-Estar Animal",
];
